### ISSUE TITLE
Problem with italic word or italic paragraph

### ISSUE THREAD

**Issue by Jbmanid** [GatoLoko/Wattpad2Epub#40] opened 2022-05-04 05:00 UTC
Thanks for the git!
But there is a problem with the results when it finds italic tags within words or paragraphs. Like the example below:
_Disclaimer_
Result:
_Disclaimer_ _Disclaimer_

other example:
Lorem Ipsum has been the industry's _standard_ dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
Result:
Lorem Ipsum has been the industry's _standard_ dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
_standard_

Another example: 
_It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged._
Result:
_It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged._
_It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged._

How to resolve this ?

**Comment by coralof** [comment] 2023-06-21 15:44
I can confirm that I'm seeing the same issue. It also happens for bold text. Whatever is bolded or italicized is repeated as the next paragraph.

**Comment by GatoLoko** [comment] 2023-11-23 00:22
Duplicate of #30

**Comment by GatoLoko** [comment] 2023-11-23 00:22
Duplicate of #30

**Closed as completed by GatoLoko** 2023-11-23 00:22 UTC
Labels: duplicate
